//! Structured table introspection, the editable "working model" behind the
//! Structure view, and per-dialect ALTER/CREATE generation.
//!
//! Flow: `Driver::describe_structure` returns a [`TableStructure`] snapshot →
//! the UI converts it into a [`WorkingTable`] (stable ids + origin snapshots)
//! → edits mutate the working model → [`generate`] diffs working vs origin and
//! emits ordered, dialect-correct DDL statements.

use super::DbKind;

/// Stable identity for an object inside one `WorkingTable`. Lets keys,
/// indexes and FKs keep referencing a column across renames.
pub type ObjId = u64;

// ---------------------------------------------------------------------------
// Introspected snapshot
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum IdentityKind {
    #[default]
    None,
    /// Postgres `GENERATED ALWAYS AS IDENTITY`
    Always,
    /// Postgres `GENERATED BY DEFAULT AS IDENTITY`
    ByDefault,
    /// MySQL `AUTO_INCREMENT`
    AutoIncrement,
    /// SQL Server `IDENTITY(1,1)`
    MsIdentity,
}

impl IdentityKind {
    pub fn label(self) -> &'static str {
        match self {
            IdentityKind::None => "none",
            IdentityKind::Always => "identity (always)",
            IdentityKind::ByDefault => "identity (by default)",
            IdentityKind::AutoIncrement => "AUTO_INCREMENT",
            IdentityKind::MsIdentity => "IDENTITY(1,1)",
        }
    }

    /// Choices offered when creating a NEW column on the given dialect.
    pub fn options(kind: DbKind) -> &'static [IdentityKind] {
        match kind {
            DbKind::Postgres => &[IdentityKind::None, IdentityKind::ByDefault, IdentityKind::Always],
            DbKind::MySql => &[IdentityKind::None, IdentityKind::AutoIncrement],
            DbKind::MsSql => &[IdentityKind::None, IdentityKind::MsIdentity],
            DbKind::Sqlite => &[IdentityKind::None, IdentityKind::AutoIncrement],
        }
    }
}

#[derive(Debug, Clone)]
pub struct ColumnInfo {
    pub name: String,
    pub type_name: String,
    pub not_null: bool,
    pub default: Option<String>,
    pub identity: IdentityKind,
    /// Generated/computed column — shown read-only, never altered.
    pub generated: bool,
    /// SQL Server: name of the default constraint backing `default`.
    pub default_constraint: Option<String>,
}

#[derive(Debug, Clone)]
pub struct KeyInfo {
    pub name: Option<String>,
    pub columns: Vec<String>,
}

#[derive(Debug, Clone)]
pub struct FkInfo {
    pub name: String,
    pub columns: Vec<String>,
    pub ref_schema: String,
    pub ref_table: String,
    pub ref_columns: Vec<String>,
    pub on_delete: String,
    pub on_update: String,
}

#[derive(Debug, Clone)]
pub struct IndexInfo {
    pub name: String,
    pub columns: Vec<String>,
    pub unique: bool,
}

#[derive(Debug, Clone)]
pub struct CheckInfo {
    pub name: String,
    pub expression: String,
}

#[derive(Debug, Clone, Default)]
pub struct TableStructure {
    pub schema: String,
    pub name: String,
    pub columns: Vec<ColumnInfo>,
    pub primary_key: Option<KeyInfo>,
    pub foreign_keys: Vec<FkInfo>,
    /// Secondary indexes only (no PK / constraint-backed indexes).
    pub indexes: Vec<IndexInfo>,
    pub checks: Vec<CheckInfo>,
}

/// Result of executing a DDL batch. Not a `Result` because a partial MySQL
/// apply is not simply an error — the caller needs the applied count.
#[derive(Debug, Clone)]
pub struct DdlOutcome {
    pub applied: usize,
    pub error: Option<String>,
}

// ---------------------------------------------------------------------------
// Working model (editable, diffable)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ChangeState {
    Unchanged,
    Added,
    Modified,
    Dropped,
}

#[derive(Debug, Clone)]
pub struct WorkingColumn {
    pub id: ObjId,
    pub name: String,
    pub type_name: String,
    pub not_null: bool,
    /// Empty string = no default.
    pub default: String,
    pub identity: IdentityKind,
    pub generated: bool,
    pub origin: Option<ColumnInfo>,
    pub dropped: bool,
}

impl WorkingColumn {
    pub fn state(&self) -> ChangeState {
        if self.dropped {
            return ChangeState::Dropped;
        }
        match &self.origin {
            None => ChangeState::Added,
            Some(o) => {
                if self.name != o.name
                    || self.type_name != o.type_name
                    || self.not_null != o.not_null
                    || norm(&self.default) != norm_opt(&o.default)
                {
                    ChangeState::Modified
                } else {
                    ChangeState::Unchanged
                }
            }
        }
    }
}

#[derive(Debug, Clone, Default)]
pub struct PkState {
    pub present: bool,
    /// Empty = let the DB pick / dialect default. Ignored on MySQL.
    pub name: String,
    pub column_ids: Vec<ObjId>,
    pub origin: Option<KeyInfo>,
    /// Ids the origin columns mapped to at load time, for rename-proof diffs.
    pub origin_ids: Vec<ObjId>,
}

impl PkState {
    pub fn state(&self) -> ChangeState {
        match (&self.origin, self.present) {
            (None, false) => ChangeState::Unchanged,
            (None, true) => ChangeState::Added,
            (Some(_), false) => ChangeState::Dropped,
            (Some(o), true) => {
                let name_changed = match &o.name {
                    Some(n) => !self.name.is_empty() && &self.name != n,
                    None => !self.name.is_empty(),
                };
                if self.column_ids != self.origin_ids || name_changed {
                    ChangeState::Modified
                } else {
                    ChangeState::Unchanged
                }
            }
        }
    }
}

#[derive(Debug, Clone)]
pub struct WorkingIndex {
    pub id: ObjId,
    pub name: String,
    pub column_ids: Vec<ObjId>,
    pub unique: bool,
    pub origin: Option<IndexInfo>,
    pub origin_ids: Vec<ObjId>,
    pub dropped: bool,
}

impl WorkingIndex {
    pub fn state(&self) -> ChangeState {
        if self.dropped {
            return ChangeState::Dropped;
        }
        match &self.origin {
            None => ChangeState::Added,
            Some(o) => {
                if self.name != o.name || self.unique != o.unique || self.column_ids != self.origin_ids {
                    ChangeState::Modified
                } else {
                    ChangeState::Unchanged
                }
            }
        }
    }
}

#[derive(Debug, Clone)]
pub struct WorkingFk {
    pub id: ObjId,
    pub name: String,
    pub column_ids: Vec<ObjId>,
    pub ref_schema: String,
    pub ref_table: String,
    /// Comma-separated referenced column list (kept as text for easy editing).
    pub ref_columns: String,
    pub on_delete: String,
    pub on_update: String,
    pub origin: Option<FkInfo>,
    pub origin_ids: Vec<ObjId>,
    pub dropped: bool,
}

impl WorkingFk {
    pub fn state(&self) -> ChangeState {
        if self.dropped {
            return ChangeState::Dropped;
        }
        match &self.origin {
            None => ChangeState::Added,
            Some(o) => {
                let ref_cols_orig = o.ref_columns.join(", ");
                if self.name != o.name
                    || self.column_ids != self.origin_ids
                    || self.ref_schema != o.ref_schema
                    || self.ref_table != o.ref_table
                    || split_cols(&self.ref_columns) != split_cols(&ref_cols_orig)
                    || self.on_delete != o.on_delete
                    || self.on_update != o.on_update
                {
                    ChangeState::Modified
                } else {
                    ChangeState::Unchanged
                }
            }
        }
    }
}

#[derive(Debug, Clone)]
pub struct WorkingCheck {
    pub id: ObjId,
    pub name: String,
    pub expression: String,
    pub origin: Option<CheckInfo>,
    pub dropped: bool,
}

impl WorkingCheck {
    pub fn state(&self) -> ChangeState {
        if self.dropped {
            return ChangeState::Dropped;
        }
        match &self.origin {
            None => ChangeState::Added,
            Some(o) => {
                if self.name != o.name || self.expression != o.expression {
                    ChangeState::Modified
                } else {
                    ChangeState::Unchanged
                }
            }
        }
    }
}

#[derive(Debug, Clone)]
pub struct WorkingTable {
    pub kind: DbKind,
    pub schema: String,
    pub name: String,
    /// `None` = brand-new table (CREATE), `Some` = existing table (ALTER).
    pub original_name: Option<String>,
    pub columns: Vec<WorkingColumn>,
    pub pk: PkState,
    pub foreign_keys: Vec<WorkingFk>,
    pub indexes: Vec<WorkingIndex>,
    pub checks: Vec<WorkingCheck>,
    next_id: ObjId,
}

impl WorkingTable {
    pub fn new_table(kind: DbKind, schema: String) -> Self {
        let mut wt = Self {
            kind,
            schema,
            name: "new_table".to_string(),
            original_name: None,
            columns: Vec::new(),
            pk: PkState::default(),
            foreign_keys: Vec::new(),
            indexes: Vec::new(),
            checks: Vec::new(),
            next_id: 1,
        };
        wt.add_column();
        wt
    }

    pub fn from_structure(kind: DbKind, ts: &TableStructure) -> Self {
        let mut next_id: ObjId = 1;
        let mut alloc = || {
            let id = next_id;
            next_id += 1;
            id
        };

        let columns: Vec<WorkingColumn> = ts
            .columns
            .iter()
            .map(|c| WorkingColumn {
                id: alloc(),
                name: c.name.clone(),
                type_name: c.type_name.clone(),
                not_null: c.not_null,
                default: c.default.clone().unwrap_or_default(),
                identity: c.identity,
                generated: c.generated,
                origin: Some(c.clone()),
                dropped: false,
            })
            .collect();

        let id_of = |name: &str| -> Option<ObjId> {
            columns.iter().find(|c| c.name == name).map(|c| c.id)
        };

        let pk = match &ts.primary_key {
            Some(k) => {
                let ids: Vec<ObjId> = k.columns.iter().filter_map(|c| id_of(c)).collect();
                PkState {
                    present: true,
                    name: k.name.clone().unwrap_or_default(),
                    column_ids: ids.clone(),
                    origin: Some(k.clone()),
                    origin_ids: ids,
                }
            }
            None => PkState::default(),
        };

        let indexes: Vec<WorkingIndex> = ts
            .indexes
            .iter()
            .map(|ix| {
                let ids: Vec<ObjId> = ix.columns.iter().filter_map(|c| id_of(c)).collect();
                WorkingIndex {
                    id: alloc(),
                    name: ix.name.clone(),
                    column_ids: ids.clone(),
                    unique: ix.unique,
                    origin: Some(ix.clone()),
                    origin_ids: ids,
                    dropped: false,
                }
            })
            .collect();

        let foreign_keys: Vec<WorkingFk> = ts
            .foreign_keys
            .iter()
            .map(|fk| {
                let ids: Vec<ObjId> = fk.columns.iter().filter_map(|c| id_of(c)).collect();
                WorkingFk {
                    id: alloc(),
                    name: fk.name.clone(),
                    column_ids: ids.clone(),
                    ref_schema: fk.ref_schema.clone(),
                    ref_table: fk.ref_table.clone(),
                    ref_columns: fk.ref_columns.join(", "),
                    on_delete: fk.on_delete.clone(),
                    on_update: fk.on_update.clone(),
                    origin: Some(fk.clone()),
                    origin_ids: ids,
                    dropped: false,
                }
            })
            .collect();

        let checks: Vec<WorkingCheck> = ts
            .checks
            .iter()
            .map(|ck| WorkingCheck {
                id: alloc(),
                name: ck.name.clone(),
                expression: ck.expression.clone(),
                origin: Some(ck.clone()),
                dropped: false,
            })
            .collect();

        Self {
            kind,
            schema: ts.schema.clone(),
            name: ts.name.clone(),
            original_name: Some(ts.name.clone()),
            columns,
            pk,
            foreign_keys,
            indexes,
            checks,
            next_id,
        }
    }

    fn alloc_id(&mut self) -> ObjId {
        let id = self.next_id;
        self.next_id += 1;
        id
    }

    pub fn add_column(&mut self) -> ObjId {
        let id = self.alloc_id();
        let n = self.columns.iter().filter(|c| c.origin.is_none()).count() + 1;
        self.columns.push(WorkingColumn {
            id,
            name: format!("column_{n}"),
            type_name: default_type(self.kind).to_string(),
            not_null: false,
            default: String::new(),
            identity: IdentityKind::None,
            generated: false,
            origin: None,
            dropped: false,
        });
        id
    }

    pub fn add_index(&mut self) -> ObjId {
        let id = self.alloc_id();
        let n = self.indexes.iter().filter(|i| i.origin.is_none()).count() + 1;
        self.indexes.push(WorkingIndex {
            id,
            name: format!("{}_idx_{n}", self.name),
            column_ids: Vec::new(),
            unique: false,
            origin: None,
            origin_ids: Vec::new(),
            dropped: false,
        });
        id
    }

    pub fn add_fk(&mut self) -> ObjId {
        let id = self.alloc_id();
        let n = self.foreign_keys.iter().filter(|f| f.origin.is_none()).count() + 1;
        self.foreign_keys.push(WorkingFk {
            id,
            name: format!("{}_fk_{n}", self.name),
            column_ids: Vec::new(),
            ref_schema: self.schema.clone(),
            ref_table: String::new(),
            ref_columns: String::new(),
            on_delete: "NO ACTION".to_string(),
            on_update: "NO ACTION".to_string(),
            origin: None,
            origin_ids: Vec::new(),
            dropped: false,
        });
        id
    }

    pub fn add_check(&mut self) -> ObjId {
        let id = self.alloc_id();
        let n = self.checks.iter().filter(|c| c.origin.is_none()).count() + 1;
        self.checks.push(WorkingCheck {
            id,
            name: format!("{}_check_{n}", self.name),
            expression: String::new(),
            origin: None,
            dropped: false,
        });
        id
    }

    pub fn col(&self, id: ObjId) -> Option<&WorkingColumn> {
        self.columns.iter().find(|c| c.id == id)
    }

    pub fn col_name(&self, id: ObjId) -> Option<&str> {
        self.col(id).map(|c| c.name.as_str())
    }

    pub fn is_pk_member(&self, id: ObjId) -> bool {
        self.pk.present && self.pk.column_ids.contains(&id)
    }

    pub fn table_renamed(&self) -> bool {
        matches!(&self.original_name, Some(o) if o != &self.name)
    }

    pub fn change_count(&self) -> usize {
        let mut n = 0;
        n += self
            .columns
            .iter()
            .filter(|c| c.state() != ChangeState::Unchanged)
            .count();
        if self.pk.state() != ChangeState::Unchanged {
            n += 1;
        }
        n += self
            .indexes
            .iter()
            .filter(|i| i.state() != ChangeState::Unchanged)
            .count();
        n += self
            .foreign_keys
            .iter()
            .filter(|f| f.state() != ChangeState::Unchanged)
            .count();
        n += self
            .checks
            .iter()
            .filter(|c| c.state() != ChangeState::Unchanged)
            .count();
        if self.table_renamed() {
            n += 1;
        }
        n
    }

    pub fn has_changes(&self) -> bool {
        self.original_name.is_none() || self.change_count() > 0
    }
}

fn default_type(kind: DbKind) -> &'static str {
    match kind {
        DbKind::Postgres => "text",
        DbKind::MySql => "varchar(255)",
        DbKind::MsSql => "nvarchar(255)",
        DbKind::Sqlite => "TEXT",
    }
}

fn norm(s: &str) -> Option<&str> {
    let t = s.trim();
    if t.is_empty() { None } else { Some(t) }
}

fn norm_opt(s: &Option<String>) -> Option<&str> {
    s.as_deref().and_then(|s| norm(s))
}

pub fn split_cols(s: &str) -> Vec<String> {
    s.split(',')
        .map(|c| c.trim().to_string())
        .filter(|c| !c.is_empty())
        .collect()
}

/// Base type names (no length/precision) for the type field autocomplete.
pub fn base_type_suggestions(kind: DbKind) -> &'static [&'static str] {
    match kind {
        DbKind::Postgres => &[
            "bigint", "boolean", "bytea", "char", "date", "double precision",
            "integer", "json", "jsonb", "numeric", "real", "smallint", "text",
            "time", "timestamp", "timestamptz", "uuid", "varchar",
        ],
        DbKind::MySql => &[
            "bigint", "blob", "boolean", "char", "date", "datetime", "decimal",
            "double", "float", "int", "json", "mediumtext", "smallint", "text",
            "time", "timestamp", "tinyint", "varbinary", "varchar",
        ],
        DbKind::MsSql => &[
            "bigint", "binary", "bit", "char", "date", "datetime2",
            "datetimeoffset", "decimal", "float", "int", "nchar", "nvarchar",
            "smallint", "time", "tinyint", "uniqueidentifier", "varbinary",
            "varchar",
        ],
        DbKind::Sqlite => &["ANY", "BLOB", "INTEGER", "NUMERIC", "REAL", "TEXT"],
    }
}

/// Label for the parameter row a base type accepts, if any.
pub fn type_params_label(base: &str) -> Option<&'static str> {
    match base.trim().to_ascii_lowercase().as_str() {
        "varchar" | "char" | "nvarchar" | "nchar" | "varbinary" | "binary"
        | "character varying" | "character" => Some("Length"),
        "numeric" | "decimal" => Some("Precision, scale"),
        _ => None,
    }
}

/// Split `varchar(255)` into (`varchar`, `255`); passthrough when no parens.
pub fn split_type(t: &str) -> (String, String) {
    match t.split_once('(') {
        Some((base, rest)) => (
            base.trim().to_string(),
            rest.trim_end().trim_end_matches(')').trim().to_string(),
        ),
        None => (t.trim().to_string(), String::new()),
    }
}

/// Recompose a base type and optional parameter list into one type name.
pub fn join_type(base: &str, params: &str) -> String {
    let base = base.trim();
    let params = params.trim();
    if params.is_empty() {
        base.to_string()
    } else {
        format!("{base}({params})")
    }
}

/// Dialect-default identity used by the column form's auto-increment toggle.
pub fn default_identity(kind: DbKind) -> IdentityKind {
    match kind {
        DbKind::Postgres => IdentityKind::ByDefault,
        DbKind::MySql | DbKind::Sqlite => IdentityKind::AutoIncrement,
        DbKind::MsSql => IdentityKind::MsIdentity,
    }
}

pub const FK_ACTIONS: &[&str] = &["NO ACTION", "RESTRICT", "CASCADE", "SET NULL", "SET DEFAULT"];

// ---------------------------------------------------------------------------
// DDL generation
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Danger {
    Safe,
    /// May fail or lose data depending on existing rows.
    Lossy,
    /// Irreversibly removes data or objects.
    Destructive,
}

#[derive(Debug, Clone)]
pub struct DdlStatement {
    /// One statement, no trailing semicolon.
    pub sql: String,
    pub danger: Danger,
    pub note: Option<&'static str>,
}

impl DdlStatement {
    fn safe(sql: String) -> Self {
        Self { sql, danger: Danger::Safe, note: None }
    }
}

pub fn script(stmts: &[DdlStatement]) -> String {
    let mut out = String::new();
    for s in stmts {
        out.push_str(&s.sql);
        out.push_str(";\n");
    }
    out
}

fn qi(kind: DbKind, name: &str) -> String {
    match kind {
        DbKind::Postgres | DbKind::Sqlite => format!("\"{}\"", name.replace('"', "\"\"")),
        DbKind::MySql => format!("`{}`", name.replace('`', "``")),
        DbKind::MsSql => format!("[{}]", name.replace(']', "]]")),
    }
}

fn qtable(kind: DbKind, schema: &str, table: &str) -> String {
    format!("{}.{}", qi(kind, schema), qi(kind, table))
}

fn ids_to_names(wt: &WorkingTable, ids: &[ObjId]) -> Vec<String> {
    ids.iter()
        .filter_map(|id| wt.col_name(*id).map(|s| s.to_string()))
        .collect()
}

fn quoted_list(kind: DbKind, names: &[String]) -> String {
    names.iter().map(|n| qi(kind, n)).collect::<Vec<_>>().join(", ")
}

/// Render a full column definition (used by ADD COLUMN, CREATE TABLE and
/// MySQL MODIFY COLUMN).
fn column_def(kind: DbKind, c: &WorkingColumn) -> String {
    let mut def = format!("{} {}", qi(kind, &c.name), c.type_name);
    match kind {
        DbKind::Postgres => {
            match c.identity {
                IdentityKind::Always => def.push_str(" GENERATED ALWAYS AS IDENTITY"),
                IdentityKind::ByDefault => def.push_str(" GENERATED BY DEFAULT AS IDENTITY"),
                _ => {
                    if let Some(d) = norm(&c.default) {
                        def.push_str(&format!(" DEFAULT {d}"));
                    }
                }
            }
            if c.not_null {
                def.push_str(" NOT NULL");
            }
        }
        DbKind::MySql => {
            if c.not_null {
                def.push_str(" NOT NULL");
            }
            if let Some(d) = norm(&c.default) {
                def.push_str(&format!(" DEFAULT {d}"));
            }
            if c.identity == IdentityKind::AutoIncrement {
                def.push_str(" AUTO_INCREMENT");
            }
        }
        DbKind::MsSql => {
            if c.identity == IdentityKind::MsIdentity {
                def.push_str(" IDENTITY(1,1)");
            }
            if c.not_null {
                def.push_str(" NOT NULL");
            }
            if let Some(d) = norm(&c.default) {
                def.push_str(&format!(" DEFAULT {d}"));
            }
        }
        DbKind::Sqlite => {
            // AUTOINCREMENT is only legal as INTEGER PRIMARY KEY AUTOINCREMENT;
            // create_table_sql appends it via the PK clause, not here.
            if c.not_null {
                def.push_str(" NOT NULL");
            }
            if let Some(d) = norm(&c.default) {
                def.push_str(&format!(" DEFAULT {d}"));
            }
        }
    }
    def
}

/// Heuristic: does changing `old` → `new` risk losing data?
fn type_change_note(old: &str, new: &str) -> Option<&'static str> {
    fn base_and_len(t: &str) -> (String, Option<u64>) {
        let t = t.trim().to_ascii_lowercase();
        match t.split_once('(') {
            Some((b, rest)) => {
                let len = rest
                    .trim_end_matches(')')
                    .split(',')
                    .next()
                    .and_then(|n| n.trim().parse::<u64>().ok());
                (b.trim().to_string(), len)
            }
            None => (t, None),
        }
    }
    fn family(base: &str) -> &'static str {
        match base {
            "tinyint" | "smallint" | "int" | "integer" | "mediumint" | "bigint" | "int2"
            | "int4" | "int8" | "serial" | "bigserial" => "int",
            "varchar" | "char" | "text" | "nvarchar" | "nchar" | "character varying"
            | "character" | "bpchar" | "tinytext" | "mediumtext" | "longtext" => "text",
            "numeric" | "decimal" | "float" | "double" | "double precision" | "real"
            | "money" => "num",
            _ => "other",
        }
    }
    fn int_rank(base: &str) -> u8 {
        match base {
            "tinyint" => 1,
            "smallint" | "int2" => 2,
            "mediumint" => 3,
            "int" | "integer" | "int4" | "serial" => 4,
            "bigint" | "int8" | "bigserial" => 8,
            _ => 0,
        }
    }

    let (ob, ol) = base_and_len(old);
    let (nb, nl) = base_and_len(new);
    if ob == nb && ol == nl {
        return None;
    }
    let (of, nf) = (family(&ob), family(&nb));
    if of != nf {
        return Some("type family change — may fail or lose data");
    }
    match of {
        "text" => {
            // text-ish → bounded, or shrinking bound
            match (ol, nl) {
                (Some(o), Some(n)) if n < o => Some("shorter length — may truncate"),
                (None, Some(_)) if ob.contains("text") => Some("unbounded → bounded — may truncate"),
                _ => None,
            }
        }
        "int" => {
            let (or, nr) = (int_rank(&ob), int_rank(&nb));
            if nr > 0 && or > 0 && nr < or {
                Some("smaller integer — may overflow")
            } else {
                None
            }
        }
        "num" => match (ol, nl) {
            (Some(o), Some(n)) if n < o => Some("lower precision — may lose precision"),
            _ => None,
        },
        _ => None,
    }
}

/// DROP TABLE, used by compare-driven migration scripts for tables that
/// exist only on the target side.
pub fn drop_table_stmt(kind: DbKind, schema: &str, table: &str) -> DdlStatement {
    DdlStatement {
        sql: format!("DROP TABLE {}", qtable(kind, schema, table)),
        danger: Danger::Destructive,
        note: Some("destructive — table and data are lost"),
    }
}

pub fn generate(wt: &WorkingTable) -> Vec<DdlStatement> {
    match &wt.original_name {
        None => generate_create(wt),
        Some(orig) if wt.kind == DbKind::Sqlite => generate_alter_sqlite(wt, orig),
        Some(orig) => generate_alter(wt, orig),
    }
}

fn generate_create(wt: &WorkingTable) -> Vec<DdlStatement> {
    let kind = wt.kind;
    let tbl = qtable(kind, &wt.schema, &wt.name);
    let mut parts: Vec<String> = Vec::new();

    // SQLite AUTOINCREMENT only exists as `INTEGER PRIMARY KEY AUTOINCREMENT`
    // on the column itself, replacing the table-level PK clause.
    let sqlite_autoinc_pk = kind == DbKind::Sqlite
        && wt.pk.present
        && wt.pk.column_ids.len() == 1
        && wt
            .columns
            .iter()
            .any(|c| {
                !c.dropped
                    && Some(c.id) == wt.pk.column_ids.first().copied()
                    && c.identity == IdentityKind::AutoIncrement
            });

    for c in wt.columns.iter().filter(|c| !c.dropped) {
        if sqlite_autoinc_pk && Some(c.id) == wt.pk.column_ids.first().copied() {
            let mut def = format!("{} INTEGER PRIMARY KEY AUTOINCREMENT", qi(kind, &c.name));
            if c.not_null {
                def.push_str(" NOT NULL");
            }
            parts.push(format!("    {def}"));
            continue;
        }
        parts.push(format!("    {}", column_def(kind, c)));
    }
    if wt.pk.present && !wt.pk.column_ids.is_empty() && !sqlite_autoinc_pk {
        let cols = quoted_list(kind, &ids_to_names(wt, &wt.pk.column_ids));
        if wt.pk.name.trim().is_empty() || kind == DbKind::MySql {
            parts.push(format!("    PRIMARY KEY ({cols})"));
        } else {
            parts.push(format!(
                "    CONSTRAINT {} PRIMARY KEY ({cols})",
                qi(kind, wt.pk.name.trim())
            ));
        }
    }
    for ck in wt.checks.iter().filter(|c| !c.dropped) {
        if norm(&ck.expression).is_some() {
            parts.push(format!(
                "    CONSTRAINT {} CHECK ({})",
                qi(kind, &ck.name),
                ck.expression.trim()
            ));
        }
    }
    for fk in wt.foreign_keys.iter().filter(|f| !f.dropped) {
        if let Some(sql) = fk_clause(wt, fk) {
            parts.push(format!("    {sql}"));
        }
    }

    let mut out = Vec::new();
    if parts.is_empty() {
        return out;
    }
    out.push(DdlStatement::safe(format!(
        "CREATE TABLE {tbl} (\n{}\n)",
        parts.join(",\n")
    )));
    for ix in wt.indexes.iter().filter(|i| !i.dropped) {
        if let Some(stmt) = create_index_sql(wt, ix, &wt.name) {
            out.push(DdlStatement::safe(stmt));
        }
    }
    out
}

fn fk_clause(wt: &WorkingTable, fk: &WorkingFk) -> Option<String> {
    let kind = wt.kind;
    let cols = ids_to_names(wt, &fk.column_ids);
    let ref_cols = split_cols(&fk.ref_columns);
    if cols.is_empty() || ref_cols.is_empty() || fk.ref_table.trim().is_empty() {
        return None;
    }
    let mut sql = format!(
        "CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {} ({})",
        qi(kind, &fk.name),
        quoted_list(kind, &cols),
        qtable(kind, fk.ref_schema.trim(), fk.ref_table.trim()),
        quoted_list(kind, &ref_cols),
    );
    if fk.on_delete != "NO ACTION" {
        sql.push_str(&format!(" ON DELETE {}", fk.on_delete));
    }
    if fk.on_update != "NO ACTION" {
        sql.push_str(&format!(" ON UPDATE {}", fk.on_update));
    }
    Some(sql)
}

fn create_index_sql(wt: &WorkingTable, ix: &WorkingIndex, table: &str) -> Option<String> {
    let kind = wt.kind;
    let cols = ids_to_names(wt, &ix.column_ids);
    if cols.is_empty() || ix.name.trim().is_empty() {
        return None;
    }
    let unique = if ix.unique { "UNIQUE " } else { "" };
    Some(format!(
        "CREATE {unique}INDEX {} ON {} ({})",
        qi(kind, ix.name.trim()),
        qtable(kind, &wt.schema, table),
        quoted_list(kind, &cols),
    ))
}

fn drop_index_sql(kind: DbKind, schema: &str, table: &str, name: &str) -> String {
    match kind {
        DbKind::Postgres | DbKind::Sqlite => {
            format!("DROP INDEX {}.{}", qi(kind, schema), qi(kind, name))
        }
        DbKind::MySql | DbKind::MsSql => format!(
            "DROP INDEX {} ON {}",
            qi(kind, name),
            qtable(kind, schema, table)
        ),
    }
}

fn generate_alter(wt: &WorkingTable, orig_table: &str) -> Vec<DdlStatement> {
    let kind = wt.kind;
    // Everything references the ORIGINAL table name; the table rename, if
    // any, is emitted last.
    let tbl = qtable(kind, &wt.schema, orig_table);
    let mut out: Vec<DdlStatement> = Vec::new();

    // 1. Drop foreign keys (dropped or modified).
    for fk in &wt.foreign_keys {
        let st = fk.state();
        if let Some(o) = &fk.origin {
            if st == ChangeState::Dropped || st == ChangeState::Modified {
                let sql = match kind {
                    DbKind::MySql => format!("ALTER TABLE {tbl} DROP FOREIGN KEY {}", qi(kind, &o.name)),
                    _ => format!("ALTER TABLE {tbl} DROP CONSTRAINT {}", qi(kind, &o.name)),
                };
                out.push(DdlStatement {
                    sql,
                    danger: if st == ChangeState::Dropped { Danger::Destructive } else { Danger::Safe },
                    note: None,
                });
            }
        }
    }

    // 2. Drop checks (dropped or modified).
    for ck in &wt.checks {
        let st = ck.state();
        if let Some(o) = &ck.origin {
            if st == ChangeState::Dropped || st == ChangeState::Modified {
                let sql = match kind {
                    DbKind::MySql => format!("ALTER TABLE {tbl} DROP CHECK {}", qi(kind, &o.name)),
                    _ => format!("ALTER TABLE {tbl} DROP CONSTRAINT {}", qi(kind, &o.name)),
                };
                out.push(DdlStatement::safe(sql));
            }
        }
    }

    // 3. Drop indexes (dropped or modified).
    for ix in &wt.indexes {
        let st = ix.state();
        if let Some(o) = &ix.origin {
            if st == ChangeState::Dropped || st == ChangeState::Modified {
                out.push(DdlStatement::safe(drop_index_sql(kind, &wt.schema, orig_table, &o.name)));
            }
        }
    }

    // 4. Drop primary key (removed or modified).
    let pk_state = wt.pk.state();
    if let Some(o) = &wt.pk.origin {
        if pk_state == ChangeState::Dropped || pk_state == ChangeState::Modified {
            let sql = match kind {
                DbKind::MySql => format!("ALTER TABLE {tbl} DROP PRIMARY KEY"),
                _ => {
                    let name = o.name.clone().unwrap_or_default();
                    format!("ALTER TABLE {tbl} DROP CONSTRAINT {}", qi(kind, &name))
                }
            };
            out.push(DdlStatement {
                sql,
                danger: if pk_state == ChangeState::Dropped { Danger::Destructive } else { Danger::Safe },
                note: None,
            });
        }
    }

    // 5. Drop columns.
    for c in wt.columns.iter().filter(|c| c.dropped && c.origin.is_some()) {
        let o = c.origin.as_ref().unwrap();
        if kind == DbKind::MsSql {
            if let Some(dc) = &o.default_constraint {
                out.push(DdlStatement::safe(format!(
                    "ALTER TABLE {tbl} DROP CONSTRAINT {}",
                    qi(kind, dc)
                )));
            }
        }
        out.push(DdlStatement {
            sql: format!("ALTER TABLE {tbl} DROP COLUMN {}", qi(kind, &o.name)),
            danger: Danger::Destructive,
            note: Some("destructive — column data is lost"),
        });
    }

    // 6. Rename columns.
    for c in wt.columns.iter().filter(|c| !c.dropped) {
        if let Some(o) = &c.origin {
            if c.name != o.name {
                let sql = match kind {
                    DbKind::MsSql => format!(
                        "EXEC sp_rename N'{}.{}.{}', N'{}', 'COLUMN'",
                        wt.schema, orig_table, o.name, c.name
                    ),
                    _ => format!(
                        "ALTER TABLE {tbl} RENAME COLUMN {} TO {}",
                        qi(kind, &o.name),
                        qi(kind, &c.name)
                    ),
                };
                out.push(DdlStatement::safe(sql));
            }
        }
    }

    // 7. Add columns.
    for c in wt.columns.iter().filter(|c| !c.dropped && c.origin.is_none()) {
        let keyword = match kind {
            DbKind::MsSql => "ADD",
            _ => "ADD COLUMN",
        };
        let lossy = c.not_null && norm(&c.default).is_none() && c.identity == IdentityKind::None;
        out.push(DdlStatement {
            sql: format!("ALTER TABLE {tbl} {keyword} {}", column_def(kind, c)),
            danger: if lossy { Danger::Lossy } else { Danger::Safe },
            note: lossy.then_some("NOT NULL without default — fails if the table has rows"),
        });
    }

    // 8. Alter existing columns (type / null / default).
    for c in wt.columns.iter().filter(|c| !c.dropped && !c.generated) {
        let Some(o) = &c.origin else { continue };
        let type_changed = c.type_name != o.type_name;
        let null_changed = c.not_null != o.not_null;
        let default_changed = norm(&c.default) != norm_opt(&o.default);
        if !(type_changed || null_changed || default_changed) {
            continue;
        }
        let col = qi(kind, &c.name);
        match kind {
            DbKind::Postgres => {
                if type_changed {
                    let note = type_change_note(&o.type_name, &c.type_name);
                    out.push(DdlStatement {
                        sql: format!("ALTER TABLE {tbl} ALTER COLUMN {col} TYPE {}", c.type_name),
                        danger: if note.is_some() { Danger::Lossy } else { Danger::Safe },
                        note,
                    });
                }
                if null_changed {
                    if c.not_null {
                        out.push(DdlStatement {
                            sql: format!("ALTER TABLE {tbl} ALTER COLUMN {col} SET NOT NULL"),
                            danger: Danger::Lossy,
                            note: Some("fails if NULL values exist"),
                        });
                    } else {
                        out.push(DdlStatement::safe(format!(
                            "ALTER TABLE {tbl} ALTER COLUMN {col} DROP NOT NULL"
                        )));
                    }
                }
                if default_changed {
                    let sql = match norm(&c.default) {
                        Some(d) => format!("ALTER TABLE {tbl} ALTER COLUMN {col} SET DEFAULT {d}"),
                        None => format!("ALTER TABLE {tbl} ALTER COLUMN {col} DROP DEFAULT"),
                    };
                    out.push(DdlStatement::safe(sql));
                }
            }
            DbKind::MySql => {
                // One MODIFY covers type + null + default.
                let note = if type_changed {
                    type_change_note(&o.type_name, &c.type_name)
                } else if null_changed && c.not_null {
                    Some("fails if NULL values exist")
                } else {
                    None
                };
                out.push(DdlStatement {
                    sql: format!("ALTER TABLE {tbl} MODIFY COLUMN {}", column_def(kind, c)),
                    danger: if note.is_some() { Danger::Lossy } else { Danger::Safe },
                    note,
                });
            }
            DbKind::MsSql => {
                if type_changed || null_changed {
                    let nullness = if c.not_null { "NOT NULL" } else { "NULL" };
                    let note = if type_changed {
                        type_change_note(&o.type_name, &c.type_name)
                    } else if c.not_null {
                        Some("fails if NULL values exist")
                    } else {
                        None
                    };
                    out.push(DdlStatement {
                        sql: format!(
                            "ALTER TABLE {tbl} ALTER COLUMN {col} {} {nullness}",
                            c.type_name
                        ),
                        danger: if note.is_some() { Danger::Lossy } else { Danger::Safe },
                        note,
                    });
                }
                if default_changed {
                    if let Some(dc) = &o.default_constraint {
                        out.push(DdlStatement::safe(format!(
                            "ALTER TABLE {tbl} DROP CONSTRAINT {}",
                            qi(kind, dc)
                        )));
                    }
                    if let Some(d) = norm(&c.default) {
                        out.push(DdlStatement::safe(format!(
                            "ALTER TABLE {tbl} ADD DEFAULT {d} FOR {col}"
                        )));
                    }
                }
            }
            // SQLite goes through generate_alter_sqlite, never here.
            DbKind::Sqlite => unreachable!(),
        }
    }

    // 9. Add primary key (new or recreated after modify).
    if wt.pk.present
        && !wt.pk.column_ids.is_empty()
        && (pk_state == ChangeState::Added || pk_state == ChangeState::Modified)
    {
        let cols = quoted_list(kind, &ids_to_names(wt, &wt.pk.column_ids));
        let sql = if kind == DbKind::MySql || wt.pk.name.trim().is_empty() {
            format!("ALTER TABLE {tbl} ADD PRIMARY KEY ({cols})")
        } else {
            format!(
                "ALTER TABLE {tbl} ADD CONSTRAINT {} PRIMARY KEY ({cols})",
                qi(kind, wt.pk.name.trim())
            )
        };
        out.push(DdlStatement {
            sql,
            danger: Danger::Lossy,
            note: Some("fails on duplicate or NULL key values"),
        });
    }

    // 10. Create indexes (added or recreated).
    for ix in &wt.indexes {
        let st = ix.state();
        if st == ChangeState::Added || st == ChangeState::Modified {
            if let Some(stmt) = create_index_sql(wt, ix, orig_table) {
                out.push(DdlStatement {
                    sql: stmt,
                    danger: if ix.unique { Danger::Lossy } else { Danger::Safe },
                    note: ix.unique.then_some("unique — fails on duplicate values"),
                });
            }
        }
    }

    // 11. Add checks (added or recreated).
    for ck in &wt.checks {
        let st = ck.state();
        if (st == ChangeState::Added || st == ChangeState::Modified) && norm(&ck.expression).is_some() {
            out.push(DdlStatement {
                sql: format!(
                    "ALTER TABLE {tbl} ADD CONSTRAINT {} CHECK ({})",
                    qi(kind, &ck.name),
                    ck.expression.trim()
                ),
                danger: Danger::Lossy,
                note: Some("fails if existing rows violate the check"),
            });
        }
    }

    // 12. Add foreign keys (added or recreated).
    for fk in &wt.foreign_keys {
        let st = fk.state();
        if st == ChangeState::Added || st == ChangeState::Modified {
            if let Some(clause) = fk_clause(wt, fk) {
                out.push(DdlStatement {
                    sql: format!("ALTER TABLE {tbl} ADD {clause}"),
                    danger: Danger::Lossy,
                    note: Some("fails if existing rows violate the reference"),
                });
            }
        }
    }

    // 13. Rename table, last so everything above targets the old name.
    if wt.table_renamed() {
        let sql = match kind {
            DbKind::Postgres | DbKind::Sqlite => {
                format!("ALTER TABLE {tbl} RENAME TO {}", qi(kind, &wt.name))
            }
            DbKind::MySql => format!(
                "RENAME TABLE {tbl} TO {}",
                qtable(kind, &wt.schema, &wt.name)
            ),
            DbKind::MsSql => format!("EXEC sp_rename N'{}.{}', N'{}'", wt.schema, orig_table, wt.name),
        };
        out.push(DdlStatement::safe(sql));
    }

    out
}

/// SQLite has no ALTER COLUMN and no ADD/DROP CONSTRAINT. Changes it does
/// support (rename table, rename/add/drop column, index add/drop) become
/// direct statements; anything else (type/null/default edits, PK/FK/check
/// changes) triggers the canonical table rebuild: CREATE a new table under a
/// temporary name, INSERT…SELECT the rows across, DROP the old table, RENAME.
fn generate_alter_sqlite(wt: &WorkingTable, orig_table: &str) -> Vec<DdlStatement> {
    let kind = wt.kind;
    let needs_rebuild = wt.pk.state() != ChangeState::Unchanged
        || wt.foreign_keys.iter().any(|f| f.state() != ChangeState::Unchanged)
        || wt.checks.iter().any(|c| c.state() != ChangeState::Unchanged)
        || wt.columns.iter().any(|c| {
            let Some(o) = &c.origin else { return false };
            !c.dropped
                && (c.type_name != o.type_name
                    || c.not_null != o.not_null
                    || norm(&c.default) != norm_opt(&o.default)
                    || c.identity != o.identity)
        });

    let tbl = qtable(kind, &wt.schema, orig_table);
    let mut out: Vec<DdlStatement> = Vec::new();

    if !needs_rebuild {
        for ix in &wt.indexes {
            let st = ix.state();
            if let Some(o) = &ix.origin {
                if st == ChangeState::Dropped || st == ChangeState::Modified {
                    out.push(DdlStatement::safe(drop_index_sql(kind, &wt.schema, orig_table, &o.name)));
                }
            }
        }
        for c in wt.columns.iter().filter(|c| c.dropped && c.origin.is_some()) {
            let o = c.origin.as_ref().unwrap();
            out.push(DdlStatement {
                sql: format!("ALTER TABLE {tbl} DROP COLUMN {}", qi(kind, &o.name)),
                danger: Danger::Destructive,
                note: Some("destructive — column data is lost"),
            });
        }
        for c in wt.columns.iter().filter(|c| !c.dropped) {
            if let Some(o) = &c.origin {
                if c.name != o.name {
                    out.push(DdlStatement::safe(format!(
                        "ALTER TABLE {tbl} RENAME COLUMN {} TO {}",
                        qi(kind, &o.name),
                        qi(kind, &c.name)
                    )));
                }
            }
        }
        for c in wt.columns.iter().filter(|c| !c.dropped && c.origin.is_none()) {
            let lossy = c.not_null && norm(&c.default).is_none();
            out.push(DdlStatement {
                sql: format!("ALTER TABLE {tbl} ADD COLUMN {}", column_def(kind, c)),
                danger: if lossy { Danger::Lossy } else { Danger::Safe },
                note: lossy.then_some("SQLite requires a default for NOT NULL ADD COLUMN on non-empty tables"),
            });
        }
        for ix in &wt.indexes {
            let st = ix.state();
            if st == ChangeState::Added || st == ChangeState::Modified {
                if let Some(stmt) = create_index_sql(wt, ix, orig_table) {
                    out.push(DdlStatement {
                        sql: stmt,
                        danger: if ix.unique { Danger::Lossy } else { Danger::Safe },
                        note: ix.unique.then_some("unique — fails on duplicate values"),
                    });
                }
            }
        }
        if wt.table_renamed() {
            out.push(DdlStatement::safe(format!(
                "ALTER TABLE {tbl} RENAME TO {}",
                qi(kind, &wt.name)
            )));
        }
        return out;
    }

    // Rebuild path.
    let tmp_name = format!("{}__new", wt.name);
    let mut tmp_wt = wt.clone();
    tmp_wt.name = tmp_name.clone();
    tmp_wt.original_name = None;
    let Some(create) = generate_create(&tmp_wt).into_iter().next() else {
        return out;
    };
    out.push(DdlStatement {
        sql: create.sql,
        danger: Danger::Lossy,
        note: Some("table rebuild — creates a new table and copies every row"),
    });

    let pairs: Vec<(&str, &str)> = wt
        .columns
        .iter()
        .filter(|c| !c.dropped && c.origin.is_some())
        .map(|c| (c.name.as_str(), c.origin.as_ref().unwrap().name.as_str()))
        .collect();
    if !pairs.is_empty() {
        let new_cols: Vec<String> = pairs.iter().map(|(n, _)| qi(kind, n)).collect();
        let old_cols: Vec<String> = pairs.iter().map(|(_, o)| qi(kind, o)).collect();
        out.push(DdlStatement::safe(format!(
            "INSERT INTO {} ({}) SELECT {} FROM {tbl}",
            qtable(kind, &wt.schema, &tmp_name),
            new_cols.join(", "),
            old_cols.join(", "),
        )));
    }
    out.push(DdlStatement {
        sql: format!("DROP TABLE {tbl}"),
        danger: Danger::Destructive,
        note: Some("old table dropped after the copy"),
    });
    out.push(DdlStatement::safe(format!(
        "ALTER TABLE {} RENAME TO {}",
        qtable(kind, &wt.schema, &tmp_name),
        qi(kind, &wt.name)
    )));
    for ix in wt.indexes.iter().filter(|i| !i.dropped) {
        if let Some(stmt) = create_index_sql(wt, ix, &wt.name) {
            out.push(DdlStatement {
                sql: stmt,
                danger: if ix.unique { Danger::Lossy } else { Danger::Safe },
                note: ix.unique.then_some("unique — fails on duplicate values"),
            });
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn snapshot() -> TableStructure {
        TableStructure {
            schema: "public".into(),
            name: "users".into(),
            columns: vec![
                ColumnInfo {
                    name: "id".into(),
                    type_name: "bigint".into(),
                    not_null: true,
                    default: None,
                    identity: IdentityKind::ByDefault,
                    generated: false,
                    default_constraint: None,
                },
                ColumnInfo {
                    name: "email".into(),
                    type_name: "varchar(100)".into(),
                    not_null: false,
                    default: None,
                    identity: IdentityKind::None,
                    generated: false,
                    default_constraint: None,
                },
            ],
            primary_key: Some(KeyInfo { name: Some("users_pkey".into()), columns: vec!["id".into()] }),
            foreign_keys: vec![],
            indexes: vec![IndexInfo {
                name: "users_email_idx".into(),
                columns: vec!["email".into()],
                unique: false,
            }],
            checks: vec![],
        }
    }

    fn sqls(wt: &WorkingTable) -> Vec<String> {
        generate(wt).into_iter().map(|s| s.sql).collect()
    }

    #[test]
    fn no_changes_no_statements() {
        let wt = WorkingTable::from_structure(DbKind::Postgres, &snapshot());
        assert!(sqls(&wt).is_empty());
        assert_eq!(wt.change_count(), 0);
    }

    #[test]
    fn rename_does_not_recreate_dependent_index() {
        let mut wt = WorkingTable::from_structure(DbKind::Postgres, &snapshot());
        wt.columns[1].name = "email_address".into();
        let out = sqls(&wt);
        assert_eq!(
            out,
            vec![r#"ALTER TABLE "public"."users" RENAME COLUMN "email" TO "email_address""#]
        );
    }

    #[test]
    fn pg_add_drop_and_retype() {
        let mut wt = WorkingTable::from_structure(DbKind::Postgres, &snapshot());
        wt.columns[1].type_name = "varchar(50)".into(); // narrowing → lossy
        wt.columns[1].dropped = false;
        let id = wt.add_column();
        {
            let c = wt.columns.iter_mut().find(|c| c.id == id).unwrap();
            c.name = "created_at".into();
            c.type_name = "timestamptz".into();
            c.default = "now()".into();
            c.not_null = true;
        }
        let stmts = generate(&wt);
        let out: Vec<&str> = stmts.iter().map(|s| s.sql.as_str()).collect();
        assert_eq!(
            out,
            vec![
                r#"ALTER TABLE "public"."users" ADD COLUMN "created_at" timestamptz DEFAULT now() NOT NULL"#,
                r#"ALTER TABLE "public"."users" ALTER COLUMN "email" TYPE varchar(50)"#,
            ]
        );
        assert_eq!(stmts[0].danger, Danger::Safe);
        assert_eq!(stmts[1].danger, Danger::Lossy);
    }

    #[test]
    fn mysql_combines_modify_and_uses_dialect_syntax() {
        let mut wt = WorkingTable::from_structure(DbKind::MySql, &snapshot());
        wt.columns[1].not_null = true;
        wt.columns[1].default = "'x'".into();
        wt.indexes[0].dropped = true;
        let out = sqls(&wt);
        assert_eq!(
            out,
            vec![
                "DROP INDEX `users_email_idx` ON `public`.`users`",
                "ALTER TABLE `public`.`users` MODIFY COLUMN `email` varchar(100) NOT NULL DEFAULT 'x'",
            ]
        );
    }

    #[test]
    fn drop_column_is_destructive_and_ordered_after_index_drop() {
        let mut wt = WorkingTable::from_structure(DbKind::Postgres, &snapshot());
        wt.columns[1].dropped = true;
        wt.indexes[0].dropped = true;
        let stmts = generate(&wt);
        assert_eq!(stmts.len(), 2);
        assert!(stmts[0].sql.starts_with("DROP INDEX"));
        assert!(stmts[1].sql.contains("DROP COLUMN"));
        assert_eq!(stmts[1].danger, Danger::Destructive);
    }

    #[test]
    fn table_rename_comes_last() {
        let mut wt = WorkingTable::from_structure(DbKind::Postgres, &snapshot());
        wt.name = "accounts".into();
        let id = wt.add_column();
        wt.columns.iter_mut().find(|c| c.id == id).unwrap().name = "note".into();
        let out = sqls(&wt);
        assert_eq!(out.len(), 2);
        assert!(out[0].contains(r#"ALTER TABLE "public"."users" ADD COLUMN"#));
        assert_eq!(out[1], r#"ALTER TABLE "public"."users" RENAME TO "accounts""#);
    }

    #[test]
    fn create_table_with_pk_and_index() {
        let mut wt = WorkingTable::new_table(DbKind::Postgres, "public".into());
        wt.name = "tags".into();
        let c0 = wt.columns[0].id;
        {
            let c = &mut wt.columns[0];
            c.name = "id".into();
            c.type_name = "bigint".into();
            c.not_null = true;
            c.identity = IdentityKind::ByDefault;
        }
        wt.pk.present = true;
        wt.pk.column_ids = vec![c0];
        let ix = wt.add_index();
        {
            let i = wt.indexes.iter_mut().find(|i| i.id == ix).unwrap();
            i.name = "tags_id_idx".into();
            i.column_ids = vec![c0];
            i.unique = true;
        }
        let out = sqls(&wt);
        assert_eq!(out.len(), 2);
        assert_eq!(
            out[0],
            "CREATE TABLE \"public\".\"tags\" (\n    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n    PRIMARY KEY (\"id\")\n)"
        );
        assert_eq!(
            out[1],
            r#"CREATE UNIQUE INDEX "tags_id_idx" ON "public"."tags" ("id")"#
        );
    }

    #[test]
    fn lossy_heuristics() {
        assert!(type_change_note("varchar(255)", "varchar(50)").is_some());
        assert!(type_change_note("bigint", "integer").is_some());
        assert!(type_change_note("integer", "bigint").is_none());
        assert!(type_change_note("varchar(50)", "varchar(255)").is_none());
        assert!(type_change_note("text", "integer").is_some());
    }
}
